name: Validate in Scratch Org

on:
    pull_request:
      types: [opened, synchronize, reopened]
    repository_dispatch:
      types: [validate-pr]

jobs:
    validate:
      runs-on: ubuntu-latest
      env:
          DEVHUB_AUTH_URL: ${{ secrets.DEVHUB_AUTH_URL }}

      steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.ref || github.ref }}

        - name: Install Salesforce CLI
          run: |
            npm install -g @salesforce/cli
            sf version

        - name: Create project-scratch-def.json if missing
          run: |
            if [ ! -f config/project-scratch-def.json ]; then
              mkdir -p config
              cat > config/project-scratch-def.json << 'EOF'
            {
              "orgName": "AI Generated Scratch Org",
              "edition": "Developer",
              "features": ["EnableSetPasswordInApi"],
              "settings": {
                "lightningExperienceSettings": {
                  "enableS1DesktopEnabled": true
                }
              }
            }
            EOF
            fi

        - name: Create sfdx-project.json if missing
          run: |
            if [ ! -f sfdx-project.json ]; then
              cat > sfdx-project.json << 'EOF'
            {
              "packageDirectories": [
                {
                  "path": "force-app",
                  "default": true
                }
              ],
              "sfdcLoginUrl": "https://login.salesforce.com",
              "sourceApiVersion": "59.0"
            }
            EOF
            fi

        - name: Authenticate Dev Hub (if secret exists)
          if: env.DEVHUB_AUTH_URL != ''
          run: |
            echo "Authenticating to DevHub..."
            echo "${{ secrets.DEVHUB_AUTH_URL }}" > auth-url.txt

            # Try to authenticate and set as DevHub
            sf org login sfdx-url --sfdx-url-file auth-url.txt --alias devhub --set-default-dev-hub

            # Verify it's a DevHub
            sf org display --target-org devhub --json > org-info.json
            cat org-info.json

            # Check if DevHub is enabled
            if ! grep -q '"isDevHub":true' org-info.json; then
              echo "ERROR: Authenticated org is not a DevHub. Enabling DevHub..."
              # Try to enable DevHub (this might not work depending on org type)
              sf org open --target-org devhub --path /lightning/setup/DevHub/home
            fi

            rm auth-url.txt org-info.json

        - name: Create Scratch Org (if authenticated)
          id: create-org
          if: env.DEVHUB_AUTH_URL != ''
          continue-on-error: true
          run: |
              sf org create scratch -f config/project-scratch-def.json -a scratch-org -d -y 1 -w 10
              echo "org_created=true" >> $GITHUB_OUTPUT

        - name: Deploy to Scratch Org
          if: steps.create-org.outputs.org_created == 'true'
          id: deploy
          continue-on-error: true
          run: |
            sf project deploy start -o scratch-org -w 20 2>&1 | tee deploy-output.txt

        - name: Report validation results to Replit
          if: always()
          run: |
            if [ "${{ steps.deploy.outcome }}" == "success" ]; then
              curl -X POST https://9734b75b-fbc8-4b34-a2f2-0236da170064-00-3orv9mnjgg5yz.riker.replit.dev/webhook/github-callback \
                -H "Content-Type: application/json" \
                -d '{
                  "success": true,
                  "storyId": "${{ github.event.pull_request.head.ref }}",
                  "prNumber": "${{ github.event.pull_request.number }}"
                }'
            else
              # Try to get the error from the deployment
              if [ -f deploy-output.txt ]; then
                DEPLOY_ERROR=$(grep -E "Error|Failed|error|failed" deploy-output.txt | head -20 | tr '\n' ' ' | tr '"' "'" || echo "Deployment failed")
              else
                DEPLOY_ERROR="Deployment failed - no output captured"
              fi
              
              # Send error with proper JSON escaping
              curl -X POST https://9734b75b-fbc8-4b34-a2f2-0236da170064-00-3orv9mnjgg5yz.riker.replit.dev/webhook/github-callback \
                -H "Content-Type: application/json" \
                -d @- <<EOF
              {
                "success": false,
                "storyId": "${{ github.event.pull_request.head.ref }}",
                "prNumber": "${{ github.event.pull_request.number }}",
                "errors": "${DEPLOY_ERROR}"
              }
              EOF
            fi

        - name: Run Tests
          if: steps.deploy.outcome == 'success'
          continue-on-error: true
          run: |
            sf apex test run -o scratch-org -w 10 -r human

        - name: Delete Scratch Org
          if: steps.create-org.outputs.org_created == 'true'
          run: |
            sf org delete scratch -o scratch-org -p || true

        - name: Comment on PR
          if: always()
          uses: actions/github-script@v6
          with:
           script: |
            let body = '⚠️ Validation status unknown';

              if ('${{ steps.create-org.outputs.org_created }}' !== 'true') {
                body = '⚠️ Scratch org creation failed or skipped';
              } else if ('${{ steps.deploy.outcome }}' === 'success') {
                body = '✅ Scratch org validation passed!';
              } else if ('${{ steps.deploy.outcome }}' === 'failure') {
                body = '❌ Deployment to scratch org failed';
              } else {
                body = '⚠️ Deployment skipped or had issues';
              }

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
